import { getServerSession } from 'next-auth/next';
import { authOptions } from '../auth/[...nextauth]';
import bcrypt from 'bcryptjs';
import connectToDatabase from '../../../lib/mongodb';
import User from '../../../models/User';
import { logActivity, ACTIONS } from '../../../lib/logger';
import { generateSecurePassword, generate4DigitPIN, sendWelcomeMessage } from '../../../lib/whatsapp';

export default async function handler(req, res) {
  const session = await getServerSession(req, res, authOptions);
  
  if (!session) {
    return res.status(401).json({ message: 'Unauthorized' });
  }
  
  // Only state admin and coordinators can access users
  if (session.user.role !== 'stateAdmin' && session.user.role !== 'coordinator') {
    return res.status(403).json({ message: 'Forbidden' });
  }
  
  await connectToDatabase();
  
  if (req.method === 'GET') {
    try {
      const { role } = req.query;
      
      // Build query filter
      let query = {};
      if (role) {
        query.role = role;
      }
      
      const users = await User.find(query).select('-password -pinCode');
      
      // Get ward information to populate district data
      const Ward = require('../../../models/Ward').default;
      const wards = await Ward.find({}).select('coordinator wardAdmin district');
      
      // Create a map of user districts based on their ward assignments
      const userDistrictMap = new Map();
      
      wards.forEach(ward => {
        if (ward.coordinator) {
          userDistrictMap.set(ward.coordinator.toString(), ward.district);
        }
        if (ward.wardAdmin) {
          userDistrictMap.set(ward.wardAdmin.toString(), ward.district);
        }
      });
      
      // Populate district information for users
      const usersWithDistricts = users.map(user => {
        const userObj = user.toObject();
        
        // If user doesn't have district in their profile, get it from ward assignment
        if (!userObj.district && userDistrictMap.has(user._id.toString())) {
          userObj.district = userDistrictMap.get(user._id.toString());
        }
        
        return userObj;
      });
      
      return res.status(200).json(usersWithDistricts);
    } catch (error) {
      return res.status(500).json({ message: 'Error fetching users', error: error.message });
    }
  }
  
  if (req.method === 'POST') {
    // Only state admin can create users, coordinators can only create ward admins in their district
    if (session.user.role === 'coordinator') {
      // Coordinators can only create ward admins in their own district
      if (req.body.role !== 'wardAdmin') {
        return res.status(403).json({ message: 'Coordinators can only create ward admin accounts' });
      }
      if (req.body.district && req.body.district !== session.user.district) {
        return res.status(403).json({ message: 'You can only create users in your own district' });
      }
    } else if (session.user.role !== 'stateAdmin') {
      return res.status(403).json({ message: 'Forbidden' });
    }
    
    try {
      const { name, email, password, role, district, mobileNumber, pinCode, wardId, sendWhatsApp = true } = req.body;
      
      // Validate required fields based on role
      if (!name || !role) {
        return res.status(400).json({ message: 'Name and role are required' });
      }
      
      let finalEmail = email;
      let finalPassword = password;
      let autoGeneratedPassword = false;
      
      if (role === 'stateAdmin') {
        if (!email) {
          return res.status(400).json({ message: 'Email is required for state admin' });
        }
        
        // Auto-generate password if not provided
        if (!password) {
          finalPassword = generateSecurePassword();
          autoGeneratedPassword = true;
        }
      } else {
        if (!mobileNumber) {
          return res.status(400).json({ message: 'Mobile number is required for coordinators and ward admins' });
        }
        
        if (mobileNumber.length < 10 || !/^\d+$/.test(mobileNumber)) {
          return res.status(400).json({ message: 'Mobile number must be at least 10 digits and contain only numbers' });
        }
        
        // For coordinators and ward admins, generate email and password automatically
        if (!email) {
          // Generate email from mobile number
          finalEmail = `user${mobileNumber}@wardmanagement.local`;
        }
        
        if (!password) {
          // Generate PIN for coordinators and ward admins, password for state admins
          finalPassword = role === 'stateAdmin' ? generateSecurePassword() : generate4DigitPIN();
          autoGeneratedPassword = true;
        }
        
        // PIN code validation (optional for new system)
        if (pinCode && (pinCode.length !== 4 || !/^\d+$/.test(pinCode))) {
          return res.status(400).json({ message: 'PIN code must be exactly 4 digits' });
        }
      }
      
      // Check if user already exists with this email
      if (finalEmail) {
        const existingUserEmail = await User.findOne({ email: finalEmail });
        if (existingUserEmail) {
          return res.status(400).json({ message: 'User with this email already exists' });
        }
      }
      
      // Check if user already exists with this mobile number (for coordinators and ward admins)
      if (mobileNumber && (role === 'coordinator' || role === 'wardAdmin')) {
        const existingUserMobile = await User.findOne({ 
          mobileNumber: mobileNumber.trim(),
          role: { $in: ['coordinator', 'wardAdmin'] }
        });
        
        if (existingUserMobile) {
          return res.status(400).json({ message: 'User with this mobile number already exists' });
        }
      }
      
      // Hash password
      const hashedPassword = await bcrypt.hash(finalPassword, 12);
      
      // Create new user
      const userData = {
        name,
        email: finalEmail,
        password: hashedPassword,
        role,
        createdBy: session.user.id,
      };
      
      // Add additional fields
      if (mobileNumber) {
        userData.mobileNumber = mobileNumber.trim();
      }
      
      if (pinCode) {
        userData.pinCode = pinCode.trim();
      }
      
      // Add district if provided
      if (district) {
        userData.district = district.trim();
      }
      
      const newUser = new User(userData);
      await newUser.save();
      
      // If ward admin and wardId provided, update the ward with the new admin
      if (role === 'wardAdmin' && wardId) {
        const Ward = require('../../../models/Ward').default;
        await Ward.findByIdAndUpdate(wardId, { wardAdmin: newUser._id });
      }
      
      // Send WhatsApp welcome message if mobile number is provided and sendWhatsApp is true
      let whatsappResult = null;
      if (sendWhatsApp && mobileNumber && autoGeneratedPassword) {
        try {
          whatsappResult = await sendWelcomeMessage({
            name: newUser.name,
            email: finalEmail,
            password: finalPassword,
            role: newUser.role,
            mobileNumber: mobileNumber
          });
        } catch (whatsappError) {
          console.error('WhatsApp send error:', whatsappError);
          whatsappResult = { success: false, error: whatsappError.message };
        }
      }
      
      // Log the user creation activity
      try {
        await logActivity({
          userId: session.user.id,
          action: ACTIONS.USER_CREATE,
          description: `Created user: ${newUser.name} (${newUser.role})`,
          entityType: 'User',
          entityId: newUser._id,
          metadata: { 
            userRole: newUser.role,
            district: newUser.district || null,
            wardId: wardId || null,
            autoGeneratedPassword: autoGeneratedPassword,
            whatsappSent: whatsappResult?.success || false
          },
          district: session.user.district,
          ward: session.user.ward,
          ipAddress: req.headers['x-forwarded-for'] || req.connection.remoteAddress,
          userAgent: req.headers['user-agent']
        });
      } catch (logError) {
        console.error('Failed to log user creation activity:', logError);
      }
      
      // Return user without password and PIN
      const savedUser = newUser.toObject();
      delete savedUser.password;
      delete savedUser.pinCode;
      
      return res.status(201).json({
        user: savedUser,
        autoGeneratedPassword: autoGeneratedPassword,
        generatedPassword: autoGeneratedPassword ? finalPassword : null, // Only for admin reference
        whatsappSent: whatsappResult?.success || false,
        whatsappError: whatsappResult?.error || null
      });
    } catch (error) {
      return res.status(500).json({ message: 'Error creating user', error: error.message });
    }
  }
  
  return res.status(405).json({ message: 'Method not allowed' });
}